FROM python:3.10-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo Python al contenedor
COPY carroSO.py .

# Instalar pygame
RUN pip install pygame

# Ejecutar el script
CMD ["python", "carroSO.py"]

